// app/dashboard/businesses/[cuid]/page.tsx
import { notFound } from "next/navigation";
import { currentUser } from "@clerk/nextjs/server";
import { type Metadata } from "next";
import { api } from "~/trpc/server"; // Assuming you have a TRPC server setup in "~/trpc/server"

import { BreadcrumbsComponent } from "~/components/common";
import Column from "~/components/templates/column";

export const metadata: Metadata = {
  title: `Business | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface BusinessPageProps {
  params: {
    cuid: string;
  };
}

export default async function BusinessesPage({ params }: BusinessPageProps) {
  const user = await currentUser();

  if (!user) return <div>This is an authenticated route</div>;

  const { cuid } = params;

  if (!cuid) {
    return notFound(); // Handles cases where no cuid is present in the URL
  }

  // Fetch business data by CUID
  const businessResponse = await api.business.getByCUID({ cuid });
  const business = businessResponse;

  if (!business) {
    return (
      <div className="container mx-auto p-4">
        <p>Business not found</p>
      </div>
    );
  }

  return (
    <>
    <BreadcrumbsComponent links={
        [
        {
            label: "Home", href: "/dashboard",
            current: false
        },
        {
            label: "Businesses", href: "/dashboard/businesses",
            current: false
        }, {
            label: business.name, href: `/dashboard/businesses/${business.cuid}`
            , current: true
        }]
    }/>
    <Column>
      <div className="p-4">
        {/* Render business details */}
        <p className="text-xl">{business.description}</p>
        <p className="text-sm">Location: {business.location}</p>
        <p className="text-sm">Industry: {business.industry}</p>
        <p className="text-sm">Created at: {new Date(business.createdAt).toLocaleString()}</p>
      </div>
    </Column>
    </>
    
  )
  ;
}