import { currentUser } from '@clerk/nextjs/server'


import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `Examples | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ExamplePage() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      <HeaderComponent title="Demo" 
        description="A collection of your favorite objects"
        actions={[
          {label: "New", type: "link", href: "/dashboard/-example/new"},
        ]}
      />
      
    </Column>
  );
}
