import { type Metadata } from "next";
import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';
import {OrganizationIndex } from './_components';

export const metadata: Metadata = {
  title: `Organization | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};




export default function OrganizationPage() {
  return (
    <Column>
      <HeaderComponent title="Organizations" 
        description="Organization starter"
        actions={[
          {label: "New Organization", type: "link", href: "/dashboard/organizations/new"},
        ]}
      />
      <OrganizationIndex />
    
    </Column>  
  )
}
