import { type Metadata } from "next";
import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';
import {BusinessIndex } from './_components';

export const metadata: Metadata = {
  title: `Business | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};




export default function BusinessPage() {
  return (
    <Column>
      <HeaderComponent title="Businesses" 
        description="Business starter"
        actions={[
          {label: "New Business", type: "link", href: "/dashboard/businesses/new"},
        ]}
      />
      <BusinessIndex />
    
    </Column>  
  )
}
