import { type Metadata } from "next";
import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';
import { OrganizationIndex } from '~/app/_components/Organization';
import { Organization } from "@clerk/nextjs/server";

export const metadata: Metadata = {
  title: `Organization | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};




export default function OrganizationPage() {
  return (
    <Column>
      <HeaderComponent title="Organizatons" 
        description="Organization starter"
        actions={[
          {label: "New Organization", type: "link", href: "/dashboard/organization/new"},
        ]}
      />
      [List Organizations]
    </Column>  
  )
}
