import { currentUser } from '@clerk/nextjs/server'


import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import { ExampleForm } from '~/app/_components/Example';

import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `Create Example | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default async function NewExamplePage() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      <HeaderComponent title="Demo Form" 
        description="Form to display flexibilty of FormComponent"
      />
      {/**
       * In order to keep the page 'server-side', it is necessary to pass the formConfig object to the FormComponent.
       */}
      <ExampleForm  />
    </Column>
  );
}
