import { currentUser } from '@clerk/nextjs/server'


import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import { OrganizationForm } from './../_components';

import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `Create Example | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default async function NewExamplePage() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      
      <HeaderComponent title="Create Organization" 
        description="Create a new organization"
      />
      
      <OrganizationForm  />

    </Column>
  );
}
