import { currentUser } from '@clerk/nextjs/server'


import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import { DocumentForm } from '../_documents';

import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `New Document | Piquette`,
  description: "Generated by Piquette",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default async function NewExamplePage() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      
      <HeaderComponent title="Create Document" 
        description="Create a new document"
      />
      
      <DocumentForm  />

    </Column>
  );
}
